language: node_js
node_js: 12

stages:
  - testing
  - deployment

jobs:
  includes:
  - stage: testing
    name: compile
    install: npm install
    script: npm run tsc

  - stage: testing
    name: linter
    install: npm install
    script: skip #linter